### ISSUE TITLE
Change Ports

### ISSUE THREAD

**Issue by coderbyheart** [NordicPlayground/nordic-developer-academy-coap#3]
- coap.nordicsemi.academy:5688 (unencrypted) -> 5683
- coap.nordicsemi.academy:5689 (dTLS with pre-shared key: connect:anything) -> 5684

**Comment by hkiiita** [comment]
Hi @coderbyheart request you to please review https://github.com/NordicPlayground/nordic-developer-academy-coap/pull/4

**Comment by hkiiita** [comment]
@coderbyheart Thank you so very much for your guidance and patience , i am happy to share that i ended up learning couple of things from this contribution. Thanks again !

**Comment by coderbyheart** [comment]
Thank you very much @hkbiet for taking this!
